name: sceneview_flutter
description: A demonstration of how to integrate SceneView in flutter.
version: 0.0.1
homepage: https://github.com/SceneView

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  plugin:
    platforms:
      android:
        package: io.github.sceneview.sceneview_flutter
        pluginClass: SceneviewFlutterPlugin